from turtle import *
t = Turtle()
s = Screen()
s.bgcolor('black')
t.color('red')
color('red')
pensize(2)
t.begin_fill()
for i in range(5):
    t.left(72)
    t.forward(100)
    t.right(144)
    t.forward(100)
t.end_fill()
done()
